// <auto-generated />
using System;
using BudgetManager.Data.Implementations.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetManager.Data.Migrations
{
    [DbContext(typeof(EFDbcontext))]
    [Migration("20250909103351_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetManager.Data.Implementations.EntityFramework.Entities.EFAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BalanceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BudgetManager.Data.Implementations.EntityFramework.Entities.EFCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BudgetManager.Data.Implementations.EntityFramework.Entities.EFRecurringEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ActiveTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChargeDay")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedRecurringId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RelatedRecurringId");

                    b.ToTable("Recurrings");
                });

            modelBuilder.Entity("BudgetManager.Data.Implementations.EntityFramework.Entities.EFTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecurringId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RecurringId");

                    b.HasIndex("RelatedTransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetManager.Data.Implementations.EntityFramework.Entities.EFCategoryEntity", b =>
                {
                    b.HasOne("BudgetManager.Data.Implementations.EntityFramework.Entities.EFCategoryEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BudgetManager.Data.Implementations.EntityFramework.Entities.EFRecurringEntity", b =>
                {
                    b.HasOne("BudgetManager.Data.Implementations.EntityFramework.Entities.EFAccountEntity", "Account")
                        .WithMany("Recurrings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetManager.Data.Implementations.EntityFramework.Entities.EFCategoryEntity", "Category")
                        .WithMany("Recurrings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetManager.Data.Implementations.EntityFramework.Entities.EFRecurringEntity", "RelatedRecurring")
                        .WithMany()
                        .HasForeignKey("RelatedRecurringId");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("RelatedRecurring");
                });

            modelBuilder.Entity("BudgetManager.Data.Implementations.EntityFramework.Entities.EFTransactionEntity", b =>
                {
                    b.HasOne("BudgetManager.Data.Implementations.EntityFramework.Entities.EFAccountEntity", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetManager.Data.Implementations.EntityFramework.Entities.EFCategoryEntity", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetManager.Data.Implementations.EntityFramework.Entities.EFRecurringEntity", "Recurring")
                        .WithMany()
                        .HasForeignKey("RecurringId");

                    b.HasOne("BudgetManager.Data.Implementations.EntityFramework.Entities.EFTransactionEntity", "RelatedTransaction")
                        .WithMany()
                        .HasForeignKey("RelatedTransactionId");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Recurring");

                    b.Navigation("RelatedTransaction");
                });

            modelBuilder.Entity("BudgetManager.Data.Implementations.EntityFramework.Entities.EFAccountEntity", b =>
                {
                    b.Navigation("Recurrings");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetManager.Data.Implementations.EntityFramework.Entities.EFCategoryEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Recurrings");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
